repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format src/emapper.net.sln --include
        types_or: ["c#", "vb"]
